.github/workflows/hugo-site-build.yml
docs/content/patterns/alz/Known-Issues.md
patterns/alz/alzArm.json
patterns/alz/policyAssignments/DINE-ConnectivityAssignment.json
patterns/alz/policyAssignments/DINE-IdentityAssignment.json
patterns/alz/policyAssignments/DINE-LandingZoneAssignment.json
patterns/alz/policyAssignments/DINE-ManagementAssignment.json
patterns/alz/policyAssignments/DINE-ServiceHealthAssignment.json
patterns/alz/policyDefinitions/policies.json
patterns/alz/scripts/Start-AMBACleanup.ps1
patterns/alz/templates/policies.bicep

1. Cleanup script [BUG 30923 - Several identities not found are left in the IAM of the MG](https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_backlogs/backlog/Azure%20Landing%20Zones%20Team/Stories/?workitem=30923)
2. Description and metadata addition to DINE-* policy files to correctly allow cleanup (https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_backlogs/backlog/Azure%20Landing%20Zones%20Team/Stories/?workitem=30923)
3. Added known issue about subsequent deployment to different locations
4. Removing 10 chars limitation for enterpriseScaleCompanyPrefix [BUG 30883 - Deployment on pseudo MG name longer than 10 chars fails](https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_backlogs/bac …

Fixes to remove old assignment and 10 char limit

---

patterns/alz/examples/sample-workflow.yml

The GitHub Actions workflow fails to run on Linux workers when the parameters path is using backslashes. This PR changes the path to use slashes.
1. https://github.com/Azure/azure-monitor-baseline-alerts/issues/30
None.

Bugfix - parameter path in workflow

---

docs/layouts/partials/templates/dashboard-tabs.html
docs/layouts/partials/templates/grafana/dashboard.html
docs/layouts/shortcodes/alertList.html

updated spacing issue in grafana template

updated spacing issue in grafana template

---

services/Network/frontdoors/_index.md
services/Network/frontdoors/alerts.yaml

Updating the recommendations for Azure Front Door
NA

Updating the recommendations for Azure Front Door

---

docs/layouts/shortcodes/alzMetricAlerts.html

Update alzMetricAlerts.html - Fixed spelling of Resources, on the Alerts Detail array.
1. Replaced: <html>
Support for Multiple Resoruces
to:
Support for Multiple Resources
N/A

Update alzMetricAlerts.html - Fixed spelling of Resources

---

docs/content/patterns/alz/deploy/Deploy-only-Service-Health-Alerts.md
docs/content/patterns/alz/deploy/Remediate-Policies.md

Added guidance for deploying only the service health alerts.
1. Adds documentation: Deploy-only-Service-Health-Alerts.md. For using ALZ Pattern to deploy only the service health alerts
N/A

Added guide to only deploy service health 

---

patterns/alz/alzArm.json
patterns/alz/policyDefinitions/policies.json
patterns/alz/policySetDefinitions/Deploy-Connectivity-Alerts.json
patterns/alz/policySetDefinitions/Deploy-Identity-Alerts.json
patterns/alz/policySetDefinitions/Deploy-LandingZone-Alerts.json
patterns/alz/policySetDefinitions/Deploy-Management-Alerts.json
patterns/alz/policySetDefinitions/Deploy-ServiceHealth-Alerts.json

1. Aligned API version used to deploy policy to a newer one.
2. Changed policyDefinitionId" value to not include the managementGroup().Name function which was creating template validation issue in VSCode as per GH Issue [Linked template validation failed #43](https://github.com/Azure/azure-monitor-baseline-alerts/issues/43). The change has been done on the following files:
- patterns\alz\policySteDefinitions\Deploy-Connectivity-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-Identity-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-LandinZone-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-Management-Alerts.json
- patterns\alz\policySteDefinitions\Deploy-ServiceHealth-Alerts.json
This work is related to bug [GH Issue 43: Linked template validation …

Fixing VSCode error with policies.json file

---

services/ApiManagement/_index.md
services/ApiManagement/service/_index.md
services/ApiManagement/service/alerts.yaml

I reviewed the alert rules for API Management 
1. Make visible the five rules for API Management
- [ x ] Read the Contribution Guide and ensured this PR is compliant with the guide
- [ x ] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [ x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [ x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [ x ] Ensured PR tests are passing
- [ x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

Api Mamagement Baseline rules

---

docs/content/patterns/alz/Whats-New.md

Update what´s new to include release: 2023-11-14

Release 2023-11-14

---

patterns/alz/examples/sample-pipeline.yml

Fixes an issue in the provided example pipeline where ubuntu-latest deployment fails with because of backward slashes.
1. Changed to forward slashes.

Change to forward slashes

---

services/DocumentDB/_index.md
services/DocumentDB/databaseAccounts/_index.md
services/DocumentDB/databaseAccounts/alerts.yaml

Made CosmosDB alerts visible and added references
1. Made CosmosDB alerts visible and added references
None

Cosmos DB Alerts

---

services/Web/sites/alerts.yaml

Updated App Service Web Apps Alerts 
1. Updates Web\Sites\Alerts.yaml with Web App alerts

Updated App Service Web Apps Alerts 

---

services/DataFactory/_index.md
services/DataFactory/factories/_index.md
services/DataFactory/factories/alerts.yaml

Allows data factory to be visible in AMBA, references added until line 150 
1. index.md removed "geekdochidden" Data Factory
2. index.md removed "geekdochidden" for factories
3. alerts.yaml, until line 150, alerts are visible and have references 
1. na

Adding Data Factory; factories  AMBA recommendations 

---

docs/content/patterns/alz/Whats-New.md

Updated what's new with release notes for release 2024-03-01
1. Updated what's new with release notes for release 2024-03-01

Added Release notes 2024-03-01

---

services/Network/azureFirewalls/alerts.yaml

The `alerts.yaml` file for AzureFirewall contains a wrong operator. For the alert `SNATPortUtilization` it is set to `LessThan`, but should be `GreaterThan`.
1. Changes `operator` for `SNATPortUtilization` in Services/Network/AzureFirewall/alerts.yaml

Fix operator in SNATPortUtilization AzureFirewall alert

---

tooling/export-alerts/export-alerts.py

Updated export-alerts.py to account for alerts without references
1. Updated export-alerts.py to account for alerts without references

Updated export-alerts.py to account for alerts without references

---

docs/content/patterns/alz/deploy/Deploy-only-Service-Health-Alerts.md
docs/content/patterns/alz/deploy/Deploy-with-Azure-CLI.md
docs/content/patterns/alz/deploy/Deploy-with-Azure-PowerShell.md

Update the deployment documentation and change the command to include the latest release. which currently is "2023-11-14" (new release planned for end of February)
This includes:
Powershell
CLI
GitHub workflows
ADO Pipelines
1. Currently our deployment commands in the documentation point to main. We change this to the latest release that we've tested. Now that there is more activity and multiple patterns (with more coming) we should have some extra protection from changes to the policy defintion.
1. No
- [x ] Associated it with relevant [GitHub …

AMBA Update deployment documentation with release tags

---

docs/content/patterns/specialized/avs/_index.md

This pull request adds additional alerts to be configured. These alerts are not yet covered as part of the deployment script and need to be monitored manually. The table in the description lists the names, thresholds, signal types, frequencies, and number of alert rules for each additional alert. Once the solution is deployed, feedback is requested from the user.

Add additional alerts to be configured

---

patterns/avd/avdArm.json
patterns/avd/templates/deploy.bicep

The deployment was failing due to the path for the Script files for the Automation Account being incorrect. 
1. _ArtifactsLocation parameter default location was incorrect and contained 'alz' in the path versus the newer location with 'avd' 
https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/patterns/avd/scripts/
1. N/A

JCore-FixAVD_Deployment_Failure

---

docs/content/patterns/specialized/avs/_index.md

This pull request updates the AVS alerts configuration to include a new threshold for the "Disk - Percentage Datastore Disk Used (%)" alert. The threshold has been changed from 1% to 70%. This change ensures that the alert is triggered when the disk usage reaches 70% instead of the previous threshold.

Update AVS alerts configuration

---

docs/content/patterns/specialized/sap/_index.md

1.  Additions of provider specific alerts SAP, Netweaver, Linux, MS SQL, DB2
1. None
###Reference
ADO#34894

SAP monitoring updates 3

---

.github/workflows/alz-update-policies.yml

The workflow automates the process of creating ARM templates for Azure Policies/ PolicySets. The workflow is triggered by a pull request event and uses a bicep build to generate the templates.
1. Workflow for automating updates to Policy ARM Templates
NA

Workflow to auto update ALZ policies

---

docs/content/patterns/alz/Cleaning-up-a-Deployment.md
docs/content/patterns/alz/UpdateToNewReleases/Update_to_release_2024-03-01.md
docs/content/patterns/alz/UpdateToNewReleases/Update_to_release_2024-04-12.md
docs/content/patterns/alz/UpdateToNewReleases/Update_to_release_2024-09-02.md
docs/content/patterns/alz/deploy/Deploy-only-Service-Health-Alerts.md
docs/content/patterns/alz/deploy/Deploy-with-Azure-CLI.md
docs/content/patterns/alz/deploy/Deploy-with-Azure-PowerShell.md
docs/content/patterns/alz/deploy/Remediate-Policies.md
patterns/alz/scripts/Start-AMBARemediation.ps1

…to be targeted
1. *Changed the description of parent mg from "identity, management and connectivity" to "Platform and Landing Zones" to better clarify the targeting. I was made aware of the confusion during the support to issue 328*
1. *NONE*

Updated documentation to clarify target parent management identification

---

docs/content/welcome/_index.md

Adds: Updating AMBA homepage with new and concise information about the site, improvements to reader experience, new visualizations, and comprehensive information on what AMBA/Monitoring entails.

Homepage Update _index.md

---

services/Compute/virtualMachines/templates/arm/DataDiskReadLatencyms_abddd643-e7c7-411c-b13a-64fdbb406cc8.json
services/Compute/virtualMachines/templates/arm/DataDiskWriteLatencyms_5c51e187-5b5d-428d-98d8-fb9ab4fea646.json
services/Compute/virtualMachines/templates/arm/OSDiskFreeSpacePercentage_dca7af9f-cad2-4751-a61f-77d92c2ce523.json
services/Compute/virtualMachines/templates/arm/OSDiskReadLatencyms_299ce963-728a-48c8-8b7d-e05b5f8a8f38.json
services/Compute/virtualMachines/templates/arm/OSDiskWriteLatencyms_37d9da12-88e6-4c01-8772-384920d34458.json
services/Compute/virtualMachines/templates/bicep/DataDiskReadLatencyms_abddd643-e7c7-411c-b13a-64fdbb406cc8.bicep
services/Compute/virtualMachines/templates/bicep/DataDiskWriteLatencyms_5c51e187-5b5d-428d-98d8-fb9ab4fea646.bicep
services/Compute/virtualMachines/templates/bicep/OSDiskFreeSpacePercentage_dca7af9f-cad2-4751-a61f-77d92c2ce523.bicep
services/Compute/virtualMachines/templates/bicep/OSDiskReadLatencyms_299ce963-728a-48c8-8b7d-e05b5f8a8f38.bicep
services/Compute/virtualMachines/templates/bicep/OSDiskWriteLatencyms_37d9da12-88e6-4c01-8772-384920d34458.bicep

[GitHub Action - Generate Templates] Generate templates for alerts

---

patterns/alz/alzArm.param.json
patterns/alz/policyDefinitions/policies-RecoveryServices.json
patterns/alz/policyDefinitions/policySets.json
patterns/alz/policySetDefinitions/Deploy-Management-Alerts.json
patterns/alz/policySetDefinitions/Deploy-RecoveryServices-Alerts.json
patterns/alz/templates/policies-RecoveryServices.bicep
services/RecoveryServices/vaults/Modify-RSV-ASRHealth-Alert.json

Configuring recovery services vaults to enable Azure Monitor for Azure Site Recovery.
1. **NEW:** Policy to audit/update Recovery Vault ASR Health Alerting to Azure monitor alerts
2. **Update:** Added new RSV policy to Management Initiative
3. **Update:** Added new RSV policy to Recovery Services Initiative
4. **Update:** Parameter file with new parameters
5. **Update:** Recovery Services template file
N/A
**Non compliant:**
**Remediation:**
**Compliance:**
**Monitoring Settings:**
```
"monitoringSettings": {
"azureMonitorAlertSettings": {
"alertsForAllJobFailures": "Enabled",
"alertsForAllReplicationIssues": "Enabled",
"alertsForAllFailoverIssues": "Enabled"
},
"classicAlertSettings": {
"alertsForCriticalOperations": "Disabled",
"emailNotificationsForSiteRecovery": "Disabled"
}
},
```

Alerts ASR  Modify Policy

---

patterns/avd/avdArm.json
patterns/avd/templates/deploy.bicep

Changed the index of a loop to access the RG name. Originally it was 4 and returning "microsoft.providers" but should be the RG name.
1. Replaced loop in AVD alerts
NA
- [ x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [x ] Ensured PR tests are passing
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

changed loop in AVD alerts 

---

.github/actions-pester/Test-ArmTemplates.Tests.ps1
.github/workflows/unit-test-arm-templates.yml

Add workflow and test scripts to verify ARM templates updated based on https://github.com/Azure/arm-ttk. Described in https://dev.azure.com/CSUSolEng/Guidance%20-%20Observability/_workitems/edit/37410
1. Add .github/workflows/unit-test-arm-templates.yml to run whenever a PR is made updating one or more ARM templates
2. Add .github/actions/Test-Armtemplates.Tests.ps1 which does the actual testing. 
No breaking changes.

Add workflow and tests

---

docs/content/patterns/artificial intelligence/_index.md

Update AI landing page to include AI on Azure Platforms (PaaS) and AI Specialized Workload Patterns sections

Update AI landing page to include PaaS and AI Specialized Workload Patterns sections

---

services/MachineLearningServices/workspaces/alerts.yaml

Added alert for *Not Responding Runs* after discussion with ML PG
1. *Alert for Not Responding Runs*

adding alert for not responding runs after discussion with ML PG

---

services/CognitiveServices/accounts/alerts.yaml

1. added threshold and severity for both AzureOpenAITimeToResponse and AzureOpenAIProvisionedManagedUtilizationV2

changed two AOAI alerts to visible with the proper thresholds

---

services/CognitiveServices/accounts/alerts.yaml

Update visibility of metrics in Cognitive Services alerts configuration

---

services/Network/expressRouteCircuits/alerts.yaml
services/Network/loadBalancers/alerts.yaml

Update visibility of metrics in alerts configuration to false for alerts that are not configured properly
1. Update visibility of metrics in alerts configuration to false for alerts that are not configured properly

Update visibility of metrics in alerts configuration to false for alerts that are not configured properly

---

services/Network/trafficmanagerprofiles/alerts.yaml

Update alert description for ProbeAgentCurrentEndpointStateByProfileResourceId to remove quotes around "Enabled"
1. Update alert description for ProbeAgentCurrentEndpointStateByProfileResourceId to remove quotes around "Enabled"

Update alert description for ProbeAgentCurrentEndpointStateByProfileResourceId to remove quotes around "Enabled"

---

.github/workflows/validate-yml-schema.yml
.github/yml-schemas/defaultAdminActivityLog.json
.github/yml-schemas/defaultDynamicMetric.json
.github/yml-schemas/defaultLog.json
.github/yml-schemas/defaultRHActivityLog.json
.github/yml-schemas/defaultSHActivityLog.json
.github/yml-schemas/defaultStaticMetric.json
.github/yml-schemas/validate_yml.py
services/AnalysisServices/servers/alerts.yaml

Add code to validate alert yaml schema on PR. Task is described in https://dev.azure.com/CSUSolEng/Guidance%20-%20Observability/_workitems/edit/37696
1. Adds Github action .github/workflows/validate-yml-schema.yml, which will trigger on PR.
2. Adds .github/yml-schemas directory containing the default yml schemas for the various alert types.
May cause previously accepted yml files to be rejected if changes are made since they are not meeting requirements.

Github action to validate yml schemas

---

patterns/alz/alz-portal.json

A regression was introduced by the Portal PG to the customUiDefinition experience which broke queries to ARG. This PR adds a fix to address the regression instead of waiting for a PG hotfix
None

fix: ALZ Pattern add missing `/` to fix PG bug

---

.github/CODEOWNERS

This pull request includes a minor change to the `.github/CODEOWNERS` file. The change corrects the team assignment for the `services/Compute` files to ensure the proper team is assigned for ownership.
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7L17-R17): Corrected the team assignment from `@Azure-amba-vm` to `@Azure/amba-vm` for the `services/Compute` files.
1. Fix codeowners file
None

fix: adjust syntax for amba-vm team reference

---

tooling/generate-templates/generate-templates.py
tooling/generate-templates/templates/bicep/log.bicep
tooling/generate-templates/templates/bicep/metric-dynamic.bicep
tooling/generate-templates/templates/bicep/metric-static.bicep

Fixes #505
* Fixes a bug in `generate-templates.py` and the related bicep base templates that is used for generating bicep `metricAlerts` & `scheduledQueryRules` templates that had the `dimensions` property being populated with an empty array inside already empty array `dimensions: [[]]`.
* For VS Code Bicep Extension this gives the warning `The enclosing array expected an item of type "MetricDimension", but the provided item was of type "<empty array>".bicep[BCP034](https://aka.ms/bicep/core-diagnostics#BCP034)`
* When trying to deploy the Bicep templates with this occurance you are met with the following **error**:
```
"statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment '-20250123-122657' is not valid according to the validation …
```

Fixes bug in `dimensions` property for metric & log alerts generation for Bicep templates

---

tooling/generate-templates/policy/log.json
tooling/generate-templates/templates/arm/log.json
tooling/generate-templates/templates/bicep/log.bicep

Fixes ARM template checks that were failing.  Sets autoMitigate to default true and removes muteActionDuration from log alert templates.
1. Fix AMR template checks that were failing for log alerts

Fix alert log templates for ARM and Bicep

---

docs/layouts/partials/templates/template-tabs.html

Deploy to Azure buttons in the Resources section will now use URLs to the raw files in GitHub.  This avoids issues with Azure downloading the template files.  For example, "There was an error downloading the template ... Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint."

Deploy to Azure buttons to use URLs to raw files in GitHub

---

tooling/generate-templates/policy/metric-dynamic-full-arm.json
tooling/generate-templates/policy/metric-dynamic.json
tooling/generate-templates/policy/metric-static-full-arm.json
tooling/generate-templates/policy/metric-static.json

Fix for compliance calculation when multiple alerts are in the same RG.
With 2 or more alerts compliancy calculation will always be done on the last alert returned, and not on itself.
To fix this one needs to use the name attribute to target the individual alerts for the existenceCondition to run on.
https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-deploy-if-not-exists
Not to familiar with this codebase, so best guess from my side where the change needed to occur.
Please advice if I have not correctly understood the code structure.
1. Adds name attribute with logic to: tooling/generate-templates/policy/metric-dynamic-full-arm.json
2. Adds name attribute with logic to: tooling/generate-templates/policy/metric-dynamic.json
3. Adds name attribute with logic to: …

Add name policy attribute for metric alerts both static and dynamic

---

services/Compute/virtualMachines/alerts.yaml
services/Compute/virtualMachines/templates/policy-arm/NetworkReadbytessec_b565e73f-71c8-4bb3-a792-903b67775497.json
services/Compute/virtualMachines/templates/policy-arm/NetworkWritebytessec_552ca1f1-d69d-4bc2-b044-19f81b225fd4.json
services/Compute/virtualMachines/templates/policy/NetworkReadbytessec_b565e73f-71c8-4bb3-a792-903b67775497.json
services/Compute/virtualMachines/templates/policy/NetworkWritebytessec_552ca1f1-d69d-4bc2-b044-19f81b225fd4.json
services/HybridCompute/machines/alerts.yaml
services/HybridCompute/machines/templates/policy-arm/HybridMachineNetworkReadAlert_5e223d13-112e-4f84-82ba-e03a76f6350f.json
services/HybridCompute/machines/templates/policy-arm/HybridMachineNetworkWriteAlert_bb1969d8-eaa2-45b6-bd9f-09348b1ee346.json
services/HybridCompute/machines/templates/policy/HybridMachineNetworkReadAlert_5e223d13-112e-4f84-82ba-e03a76f6350f.json
services/HybridCompute/machines/templates/policy/HybridMachineNetworkWriteAlert_bb1969d8-eaa2-45b6-bd9f-09348b1ee346.json

Fix dimensions for VM and HybridCompute Log Alerts 

Fix dimensions for VM and HybridCompute Log Alerts 

---

services/DocumentDB/databaseAccounts/alerts.yaml

Updating cosmos DB alert rules with PG signed off alerts. Many Cosmos DB alerts are now PG verified and properties/thresholds are updated, including severity levels, evaluation frequencies, time aggregation, threshold type. New ThrottledRequests alert is added, and for PG verified alerts, verification property is set to true for alert definitions.
1. *Updates existing alert rules with new signed off thresholds*
2. *Adds new "Throttled Request" alert for Cosmos DB*
3. *Sets PG verified alerts as true to show verified status*
Tested extensively to make sure failing check errors are fixed

Update alert rules for Cosmos DB

---

.github/actions-pester/Test-ModifiedPolicies.Tests.ps1

fix: refine filtering for modified and added policy files in tests

---

services/Sql/servers/alerts.yaml
services/Sql/servers/templates/policy-arm/databases-sqlinstancecpupercent_1a8132b9-fbd2-4ac5-9e08-96358e16b7f7.json
services/Sql/servers/templates/policy-arm/databases-sqlinstancememorypercent_f44a3cb0-6e99-4a5e-a691-c5d7d5bf7e64.json
services/Sql/servers/templates/policy-arm/databases-tempdbdatasize_0fe27fd1-e4f7-48c1-bbd2-a6953755d5e8.json
services/Sql/servers/templates/policy/databases-sqlinstancecpupercent_1a8132b9-fbd2-4ac5-9e08-96358e16b7f7.json
services/Sql/servers/templates/policy/databases-sqlinstancememorypercent_f44a3cb0-6e99-4a5e-a691-c5d7d5bf7e64.json
services/Sql/servers/templates/policy/databases-tempdbdatasize_0fe27fd1-e4f7-48c1-bbd2-a6953755d5e8.json
services/Storage/storageAccounts/templates/policy-arm/Availability_b1a4849b-78a8-437f-8113-7c6f2dc34927.json
services/Storage/storageAccounts/templates/policy-arm/UsedCapacity_b663a689-6db8-467d-8b5d-8cd34afe4b0e.json
services/Storage/storageAccounts/templates/policy-arm/blobServices-BlobCapacity_8c0aaea9-bcce-4c27-a090-ffe54b7e1d1c.json
services/Storage/storageAccounts/templates/policy/Availability_b1a4849b-78a8-437f-8113-7c6f2dc34927.json
services/Storage/storageAccounts/templates/policy/UsedCapacity_b663a689-6db8-467d-8b5d-8cd34afe4b0e.json
services/Storage/storageAccounts/templates/policy/blobServices-BlobCapacity_8c0aaea9-bcce-4c27-a090-ffe54b7e1d1c.json

Add kind field to a few SQL alerts to ignore elastic pool DBs

Add kind field to a few SQL alerts to ignore elastic pool DBs

---

.github/yml-schemas/defaultDynamicMetric.json
.github/yml-schemas/defaultStaticMetric.json
services/Network/expressRouteGateways/alerts.yaml
services/Network/virtualNetworkGateways/alerts.yaml
services/Network/virtualNetworkGateways/templates/policy-arm/AverageBandwidth_88642ff7-6c08-486a-9bf2-37764d5bf6a3.json
services/Network/virtualNetworkGateways/templates/policy-arm/ExpressRouteGatewayBitsPerSecond_4c3c25d2-7473-4d0c-9174-609162571859.json
services/Network/virtualNetworkGateways/templates/policy-arm/ExpressRouteGatewayCpuUtilization_56491bc7-1267-42a2-92c6-fe9efe822ff1.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelAverageBandwidth_09bb7f01-a715-437d-b692-325f89e1869e.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelEgressBytes_092f6e09-1eb5-436d-b7c2-eadb70318920.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelEgressPacketDropCount_6f02e3e8-9bfa-4312-a352-6506139e3dba.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelEgressPacketDropTSMismatch_ca909c09-89c4-467e-bdca-9140e72d6c82.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelIngressBytes_a34fa329-da3e-4947-8d06-9bd2bee6c8a7.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelIngressPacketDropCount_b511650f-535c-45d1-a089-0ea402245deb.json
services/Network/virtualNetworkGateways/templates/policy-arm/TunnelIngressPacketDropTSMismatch_1cc4a539-e4bf-40e8-a280-f4e9e178fb51.json
services/Network/virtualNetworkGateways/templates/policy/AverageBandwidth_88642ff7-6c08-486a-9bf2-37764d5bf6a3.json
services/Network/virtualNetworkGateways/templates/policy/ExpressRouteGatewayBitsPerSecond_4c3c25d2-7473-4d0c-9174-609162571859.json
services/Network/virtualNetworkGateways/templates/policy/ExpressRouteGatewayCpuUtilization_56491bc7-1267-42a2-92c6-fe9efe822ff1.json
services/Network/virtualNetworkGateways/templates/policy/TunnelAverageBandwidth_09bb7f01-a715-437d-b692-325f89e1869e.json
services/Network/virtualNetworkGateways/templates/policy/TunnelEgressBytes_092f6e09-1eb5-436d-b7c2-eadb70318920.json
services/Network/virtualNetworkGateways/templates/policy/TunnelEgressPacketDropCount_6f02e3e8-9bfa-4312-a352-6506139e3dba.json
services/Network/virtualNetworkGateways/templates/policy/TunnelEgressPacketDropTSMismatch_ca909c09-89c4-467e-bdca-9140e72d6c82.json
services/Network/virtualNetworkGateways/templates/policy/TunnelIngressBytes_a34fa329-da3e-4947-8d06-9bd2bee6c8a7.json
services/Network/virtualNetworkGateways/templates/policy/TunnelIngressPacketDropCount_b511650f-535c-45d1-a089-0ea402245deb.json
services/Network/virtualNetworkGateways/templates/policy/TunnelIngressPacketDropTSMismatch_1cc4a539-e4bf-40e8-a280-f4e9e178fb51.json
tooling/generate-templates/generate-policies-full-arm.ps1
tooling/generate-templates/generate-policies.ps1
tooling/generate-templates/policy/metric-dynamic-full-arm.json
tooling/generate-templates/policy/metric-dynamic.json
tooling/generate-templates/policy/metric-static-full-arm.json
tooling/generate-templates/policy/metric-static.json

Updated policies for type Microsoft.Network/virtualNetworkGateways to distinguish between ExpressRoute and VPN Gateway resources using the "gatewayType" property.  Also updated the descriptions for Microsoft.Network/expressRouteGateways alerts with information that those alerts apply to VWAN ExR GWs.

Update policies to distinguish between ExpressRoute and VPN 

---

docs/content/patterns/monitoring packs/IaaS/_index.md

The title is 'Nginx'. This PR fixes spelling in [IaaS monitoring pack list](https://azure.github.io/azure-monitor-baseline-alerts/patterns/monitoring-packs/IaaS/).
Changes the spelling from 'NGinx' to 'Nginx' in the Monitoring Packs of IaaS list to maintain consistency with other documentation. c.f. the [Nginx.md](https://github.com/Azure/azure-monitor-baseline-alerts/blob/14d475cc8a661331e6926c4821d3b144daec09df/docs/content/patterns/monitoring%20packs/IaaS/Nginx.md)
N/A
Links tested and working.

Fix Nginx capitalization in IaaS documentation
