Azure/azure-monitor-baseline-alerts

docs/content/patterns/alz/Disabling-Policies.md
Minor documentation updates.
1. Added link
2. Fixed typo
N/A
=> Added link to AMBARemediation script

patterns/alz/alzArm.param.json
Correction to LandingZoneManagementGroup default value.
Correction to LandingZoneManagementGroup default value.
NA
=> Update default value LandingZoneManagementGroup

docs/content/patterns/alz/Moving-from-preview-to-GA.md, docs/content/patterns/alz/deploy/_index.md
- Updated Naming for migration guidance.
- Removed "coming soon" from deployment guide
- Updated Naming for migration guidance.
- Removed "coming soon" from deployment guide
NA
=> Update moving guidance

docs/content/patterns/alz/FAQ.md, docs/content/patterns/alz/Known-Issues.md, docs/content/patterns/alz/Moving-from-preview-to-GA.md, docs/content/patterns/alz/deploy/Customize-Policy-Assignment.md, docs/content/patterns/alz/deploy/Deploy-with-Azure-CLI.md, docs/content/patterns/alz/deploy/Deploy-with-Azure-Pipelines.md, docs/content/patterns/alz/deploy/Deploy-with-Azure-PowerShell.md, docs/content/patterns/alz/deploy/Deploy-with-GitHub-Actions.md
ALZ Pattern documentation updates
1. Adds FAQ entry for Location guidance
2. Adds Information to Known Issues regarding multiples deployments with different locations
3. Updated Moving from preview to GA
4. Format update Customize Policy Assignment
5. Update "Moving from preview to GA" links in the deployment guides.
6. Update note regarding the location variable  in the deployment guides.
NA
=> Documentation updates

patterns/alz/alzArm.json
Fixes some transient deployment issues when deployed with the ALZ Accelerator. 
1. Changed the deployment name for the loop deployment from "preparingToLaunch" to "ambaPreparingToLaunch"
2. Changed the name and depends on from "policyCompletion" to "ambaPolicyCompletion"
N/A
=> Update deployment name and dependsOn

docs/content/patterns/alz/Policy-Initiatives.md
1. Fixed broken links in ALZ Policy Initiatives
=> Fixed links in Policy Initiative

docs/layouts/partials/templates/dashboard-tabs.html, docs/layouts/partials/templates/grafana/dashboard.html, docs/layouts/shortcodes/alertList.html
Added a dashboard section in the resource types and added an autogenerated Grafana dashboard template.
=> added grafana dashboard section

docs/layouts/partials/templates/grafana/dashboard.html
Fixed a spacing issue in the Grafana template
=> Fixed spacing issue in Grafana template

docs/layouts/partials/templates/grafana/dashboard.html
Fixed an issue with threshold in Grafana bug
=> fixed threshold bug for grafana dashboard

docs/layouts/partials/head/custom.html
Added telemetry to Microsoft Clarity
=> Added telemetry to Microsoft Clarity

config/_default/hugo.toml, docs/content/privacy/_index.md
=> added privacy page

docs/layouts/partials/templates/arm/log.html, docs/layouts/partials/templates/arm/metric-static.html, docs/layouts/partials/templates/bicep/log.html, docs/layouts/partials/templates/bicep/metric-dynamic.html, docs/layouts/partials/templates/bicep/metric-static.html, services/Automation/automationAccounts/alerts.yaml, services/Compute/virtualMachines/alerts.yaml, services/Network/applicationGateways/alerts.yaml
Fixed issues where the ARM and bicep templates were not valid
=> Fixed issues with ARM and bicep templates

docs/content/patterns/alz/FAQ.md
Improved readability and new FAQs
1. Improved readability
2. Private deployments template specs
=> FAQ Update

docs/content/patterns/alz/Known-Issues.md
Added a new issue occurring when the limit of 800 deployment for the given MG has been reached.
1. Add a scenario to the known issues
1. NONE
=> New known issue during deployment

services/Cache/Redis/_index.md, services/Cache/Redis/alerts.yaml, services/Cache/_index.md
Added Azure Cache for Redis Alerts
1. Added Azure Cache for Redis Alerts
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [x ] Ensured PR tests are passing
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)
=> Added Azure Cache for Redis Alerts

services/ContainerRegistry/_index.md, services/ContainerRegistry/registries/_index.md, services/ContainerRegistry/registries/alerts.yaml
Added alerts for container registry
1. Added alerts for container registry
=> Container Registry Alerts

services/ContainerService/_index.md, services/ContainerService/managedClusters/_index.md, services/ContainerService/managedClusters/alerts.yaml
Checked autogenerated alerts and made some visible based on documentation here:  https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-metric-alerts?tabs=arm-template%2Cazure-portal#recommended-alert-rules
1. Changes some generated rules to visible with reference added
None
=> Checked AKS auto generated alerts and made some visible based on docs

services/Web/sites/alerts.yaml
Fixed references array formatting
1. Fixed references array formatting
=> Fixed references array formatting

services/Databricks/_index.md, services/Databricks/workspaces/_index.md, services/Databricks/workspaces/alerts.yaml, services/ServiceFabric/_index.md, services/ServiceFabric/clusters/_index.md, services/ServiceFabric/clusters/alerts.yaml
Added folders for Databricks and Service Fabric
1. Added folders for Databricks and Service Fabric
=> Added folders for Databricks and Service Fabric

tooling/export-alerts/export-alerts.py
Updated export-alerts.py to account for empty yaml file
1. Updated export-alerts.py to account for empty yaml file
- [ x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [x ] Ensured PR tests are passing
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)
=> Updated export-alerts.py to account for empty yaml file

services/EventHub/_index.md, services/EventHub/clusters/_index.md, services/EventHub/clusters/alerts.yaml, services/EventHub/namespaces/_index.md, services/EventHub/namespaces/alerts.yaml
Made EventHubs alerts visible and added references
1. Made EventHubs alerts visible and added references
=> Made EventHubs alerts visible

services/Cdn/_index.md, services/Cdn/profiles/_index.md, services/Cdn/profiles/alerts.yaml
Made Cdn.Profiles alerts visible
1. Made Cdn.Profiles alerts visible
=> Made Cdn.Profiles alerts visible

docs/content/patterns/alz/Alerts-Details.md
Fixes 2 broken links on the Alerts-Details page
1. *link to 'Policy-initiatives*
2. *link to 'FAQ'*
- [] Read the Contribution Guide and ensured this PR is compliant with the guide
=> fixing links Policy-Initiatives and FAQ

docs/content/patterns/specialized/avs/_index.md
Revised the alert threshold and severity
=> Revised the alert threshold and severity

services/_index.md
Changed Services to Azure Resources
1. Changed Services to Azure Resources
=> Changed Services to Azure Resources

docs/content/visualizations/Azure Workbooks/_index.md
1. fixed line 20 image reference
1.  n/a
- [ x] Read the Contribution Guide and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [ x] Ensured PR tests are passing
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)
=> fixed image not rendering (ln 20)

docs/content/contributing/_index.md, docs/content/welcome/_index.md
Updated welcome pages and contribution guide to reflect name change
1. Updated welcome pages and contribution guide to reflect name change
=> Updated welcome pages and contribution guide to reflect name change

docs/layouts/partials/templates/arm/log.html, docs/layouts/partials/templates/arm/metric-dynamic.html, docs/layouts/partials/templates/arm/metric-static.html
Updated issues with ARM templates
1. Updated issues with ARM templates
=> Updated issues with ARM templates

docs/layouts/partials/templates/arm/log.html, docs/layouts/partials/templates/arm/metric-static.html
Fixed threshold value in template
1. Fixed threshold value in template
=> Fixed threshold value in template

docs/content/patterns/alz/deploy/PowerShell-ExecutionPolicy.md
1. *made PowerShell ExecutionPolicy not visible since this is a reusable include*
1. *NONE*
=> Fixing visibility issue with PowerShell ExecutionPolicy

docs/content/visualizations/Azure Dashboards/_index.md, docs/content/visualizations/Health Modeling/_index.md, docs/content/visualizations/Power BI/_index.md
Hid visualizations currently under development
1. Changes PowerBI, Azure Dashboards and Health modeling pages to be hidden.
None
=> Hid visualizations currently under development

services/Compute/virtualMachines/alerts.yaml
Added VM Log alerts back in
1. Added VM Log alerts back in
=> Added VM Log alerts back in

tooling/export-alerts/export-alerts.py
Fixed issue with export-alerts
1. Fixed issue with export-alerts
=> Fixed issue with export-alerts

docs/content/patterns/specialized/avs/_index.md
This pull request updates the AVS alerts configuration to reflect the correct thresholds and signal types for CPU and memory usage. It also adds a new alert for disk usage on datastores.
=> Update AVS alerts configuration

docs/layouts/_default/_markup/render-codeblock-mermaid.html, docs/themes/hugo-geekdoc/README.md, services/Network/loadBalancers/_index.md, services/Network/loadBalancers/alerts.yaml
1. add additional metrics to the load balancer
2. remove duplicate
3. add workflow for deciding which metric to use in each respective scenario
=> amba monitoring update for azure load balancer

services/ContainerInstance/containerGroups/alerts.yaml, services/Logic/workflows/alerts.yaml, services/Network/dnszones/alerts.yaml, services/Network/virtualNetworkGateways/alerts.yaml, services/OperationalInsights/workspaces/alerts.yaml, services/Sql/servers/alerts.yaml, services/Web/serverFarms/alerts.yaml, services/Web/sites/alerts.yaml, tooling/query-metrics-alerts/analysis_query.kql
1. Replace this with a brief description of what this Pull Request fixes, changes, etc.
=> Fixed a typo in Dynamic alert configuration

docs/content/patterns/specialized/sap/FAQ.md, docs/content/patterns/specialized/sap/Known-Issues.md, docs/content/patterns/specialized/sap/_index.md
This is initial set of SAP Monitor Alerts
1. Adds initial 18 alerts
2. FAQ
[ADO#33951](https://dev.azure.com/CSUSolEng/Accelerator%20-%20SAP/_workitems/edit/33951)
=> SAP Monitor Alerts Update 1

docs/content/patterns/specialized/avs/_index.md
This pull request adds the vSphere DRS Automation Level configuration for on-premises VCenter Server. This configuration allows for partially automated DRS in the specified scenarios.
=> Add vSphere DRS Automation Level configuration for on-premises VCenter Server

docs/content/patterns/specialized/sap/_index.md
Minor updates to SAP Alerts table
Reference  [ADO 34894](https://dev.azure.com/CSUSolEng/Accelerator%20-%20SAP/_workitems/edit/34894)
1. CPU % changed from 80,90,95 to 75,85,95
2. Removed Express Route entries
3. Removed Backup, Netweaver entries
None
=> SAP Alerts Update 2

services/Cdn/profiles/Deploy-CDNP-OriginHealthPercentage-Alert.json, services/Cdn/profiles/Deploy-CDNP-OriginLatency-Alert.json, services/Compute/virtualMachines/Deploy-VM-DataDiskReadLatency-Alert.json, services/Compute/virtualMachines/Deploy-VM-DataDiskSpace-Alert.json, services/Compute/virtualMachines/Deploy-VM-DataDiskWriteLatency-Alert.json, services/Compute/virtualMachines/Deploy-VM-HeartBeat-Alert.json, services/Compute/virtualMachines/Deploy-VM-HeartBeatAlertRG.json, services/Compute/virtualMachines/Deploy-VM-NetworkIn-Alert.json, services/Compute/virtualMachines/Deploy-VM-NetworkOut-Alert.json, services/Compute/virtualMachines/Deploy-VM-OSDiskReadLatency-Alert.json, services/Compute/virtualMachines/Deploy-VM-OSDiskSpace-Alert.json, services/Compute/virtualMachines/Deploy-VM-OSDiskWriteLatency-Alert.json, services/Compute/virtualMachines/Deploy-VM-PercentCPU-Alert.json, services/Compute/virtualMachines/Deploy-VM-PercentMemory-Alert.json
As discussed in issue #185, the parameter names are case sensitive for terraform, and it would be great if the policies would be consistent in the casing of the parameter names.
No breaking changes.
=> (fix) case sensitive parameters in policies

docs/content/patterns/specialized/avs/_index.md
=> Product Group review

docs/content/patterns/alz/Telemetry.md
1. *Adding PID for different additional deployment methods*
1. *NONE*
=> Adding PID for different additional deployment methods

README.md
1. Updated README to fix maintenance stats updates
=> Updated README to fix maintenance stats updates

services/Network/frontdoors/_index.md
=> Azure front door monitoring pattern updates

docs/content/patterns/alz/Telemetry.md, docs/content/patterns/alz/Whats-New.md
Updated the release notes to include the changes to the ALZ pattern from the latest releases.
N/A
N/A
=> Update Release notes

docs/content/patterns/alz/Bring-your-own-Managed-Identity.md, docs/content/patterns/alz/Known-Issues.md
1. *Adds a new error message content to the existing **VM Log Alert policies fail to remediate section** in the Known Issue page*
2. *Adds a new section for **Failed to deploy because of 'location' property not specified error** in the Known Issue page
3. * Adds the **Switching between BYO UAMI and new UAMI** ** in the Bring Your Own User Assigned Managed Identity (BYO UAMI) page*
All the above are related to the USer Story [AMBA - Update Known Issues and BYO UAMI documentation](https://dev.azure.com/CSUSolEng/Azure%20Landing%20Zones/_queries/edit/35143/?triage=true)
1. *NONE*
=> Updated documentation

.github/workflows/generate-templates.yml
1. Add permissions for generate-templates Action to create PR
*
=> Add permissions for generate-templates Action to create PR

docs/layouts/partials/templates/template-tabs.html
Updated policy tab for individual alerts to utilize new templated policy generation process
1. Updated policy tab for individual alerts to utilize new templated policy generation process
=> Updated policy tab for individual alerts to utilize new templated policy generation process

docs/content/visualizations/Azure Managed Grafana/_index.md
Updates the AMG visualization section with latest screenshots and links for Azure Infra Monitor dashboards.
=> Updated Grafana visualization Section

docs/content/visualizations/Azure Managed Grafana/_index.md
URL for Azure Grafana library of dashboards recently changed.  This PR updates the Grafana visualization section with the correct URL.
=> Update Grafana section with new URL to Grafana Azure Library

patterns/avd/avdArm.json
=> Adding the timezone for Italy North region

docs/content/patterns/alz/deploy/Remediate-Policies.md
1. *Adding the remediation command for Recovery Services which was missing in the documentation*
1. *NONE*
=> Adding the remediation command for Recovery Services

docs/content/patterns/monitoring packs/_index.md
Simple typo fix found on the packs documentation index.md page from the documentation site. 
N/A see above, simple .md character fix.
N/A
=> Typo fix on packs documentation page

services/AVS/privateClouds/alerts.yaml
added missing GUIDs for AVS
1. added missing GUIDs for AVS
=> added missing GUIDs for AVS

services/Search/searchServices/alerts.yaml
1. Add a delete activity alert rule for Microsoft.Search/searchServices as per the guidance in the article below.
https://learn.microsoft.com/en-us/azure/search/monitor-azure-cognitive-search#azure-ai-search-alert-rules
=> Added alert for AI search service

docs/content/patterns/artificial intelligence/_index.md, docs/content/patterns/artificial intelligence/index.md
1. updated the AI landing page location and TOC
=> updated the AI landing page location and TOC

services/MachineLearningServices/workspaces/alerts.yaml
Added alerts for Microsoft.MachineLearningServices/workspaces resource type. 
These alerts are based on the guidance provided here 
https://learn.microsoft.com/en-us/azure/machine-learning/monitor-azure-machine-learning?view=azureml-api-2#machine-learning-alert-rules
3 new metric alerts:
1. *Model Deploy Failed*
2. *Quota Utilization Percentage*
3. *Unusable Nodes*
=> Added alerts for Microsoft.MachineLearningServices/workspaces

docs/content/welcome/_index.md
This PR updates the graphic for the levels of AMBA visual representation, by adding AI to the patterns/scenarios level. This showcases to customers/field users the new AI patterns/scenarios/metrics that AMBA is supporting.
This PR also removes the "Today" text from the monitoring - experience throughout the journey image, to be more visually concise and clear to understand.
1. *Adds AI to AMBA visual level representation graphic*
2. *Updates monitoring - experience throughout the journey image to be visually clearer and concise*
- [x ] Associated it with …
=> Update to homepage - graphic enhancements

tooling/generate-templates/arm/activity-administrative.json, tooling/generate-templates/arm/activity-resourcehealth.json, tooling/generate-templates/arm/activity-servicehealth.json, tooling/generate-templates/arm/log.json, tooling/generate-templates/arm/metric-dynamic.json, tooling/generate-templates/arm/metric-static.json, tooling/generate-templates/bicep/activity-administrative.bicep, tooling/generate-templates/bicep/activity-resourcehealth.bicep, tooling/generate-templates/bicep/activity-servicehealth.bicep, tooling/generate-templates/bicep/log.bicep, tooling/generate-templates/bicep/metric-dynamic.bicep, tooling/generate-templates/bicep/metric-static.bicep
1. Updated version for Microsoft.Resources/deployments
=> Updated version for Microsoft.Resources/deployments

services/CognitiveServices/accounts/_index.md, services/CognitiveServices/accounts/alerts.yaml
=> changed old alerts to visible false. changed index to visible

docs/content/patterns/alz/UpdateToNewReleases/_index.md, docs/content/patterns/alz/Whats-New.md, docs/content/patterns/alz/deploy/Deploy-only-Service-Health-Alerts.md, docs/content/patterns/alz/deploy/Deploy-with-Azure-CLI.md, docs/content/patterns/alz/deploy/Deploy-with-Azure-PowerShell.md, docs/content/patterns/alz/deploy/parameterConfiguration.md
1. *Updated documentation*
2. *Tested AMBA accelerator deployment pointing to release 2024-11-01
1. *NONE*
=> Updating documentation following to the latest release

docs/content/patterns/specialized/sap/_index.md
Corrected signal type from metric alerts to log analytics for SAP.  Added link for Managed Alerts (Bulk view and edit).
1. Change Metric alerts to Log Analytics
2. Added Managed Alerts link
3. Corrected missing link to FAQ
- [  ] Read the Contribution Guide and ensured this PR is compliant with the guide
- [  ] Checked for duplicate [Pull Requests](https://github.com/Azure/azure-monitor-baseline-alerts/pulls)
- [  ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [  ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
- [  ] Ensured PR tests are passing
- [  ] Updated relevant and associated documentation …
=> SAP AMBA update - bulk alerts

.github/ISSUE_TEMPLATE/amba-alz-issue.yml, .github/ISSUE_TEMPLATE/amba-avd-issue.yml, .github/ISSUE_TEMPLATE/amba-avs-issue.yml
Assign correct assignees in issue template, as per https://dev.azure.com/CSUSolEng/Guidance%20-%20Observability/_workitems/edit/37047
1. changes assignees in the following issue templates
- amba-alz-issue.yml
- amba-avd-issue.yml
- amba-avs-issue.yml
N/A
=> Assignees in issue templates

.github/ISSUE_TEMPLATE/amba-alz-issue.yml
Add 🚁 to Pattern: ALZ label
1. Updates .github/ISSUE_TEMPLATE/amba-alz-issue.yml with the label
N/A
=> Inlcude :helicopter: in labels

services/HybridCompute/machines/templates/arm/HybridMachineAvailableMemoryPercentage_67300599-c61e-48d2-b47d-979b2254d494.json, services/HybridCompute/machines/templates/arm/HybridMachineDataDiskFreeSpacePercentageAlert_2030d931-6431-4134-9a03-106ebb83cb2d.json, services/HybridCompute/machines/templates/arm/HybridMachineDataDiskReadLatencyAlert_6aff7331-001f-4ee6-b5d2-1fc43b18b7de.json, services/HybridCompute/machines/templates/arm/HybridMachineDataDiskWriteLatencyAlert_c4226730-ae59-4607-bddc-03b91dad1c4b.json, services/HybridCompute/machines/templates/arm/HybridMachineHeartbeatAlert_7ade7362-3df1-4ad2-a000-78fa7b3d9b27.json, services/HybridCompute/machines/templates/arm/HybridMachineNetworkReadAlert_5e223d13-112e-4f84-82ba-e03a76f6350f.json, services/HybridCompute/machines/templates/arm/HybridMachineNetworkWriteAlert_bb1969d8-eaa2-45b6-bd9f-09348b1ee346.json, services/HybridCompute/machines/templates/arm/HybridMachineOSDiskFreeSpacePercentage_6a96dc94-674f-4a9c-830e-a0a4f7383646.json, services/HybridCompute/machines/templates/arm/HybridMachineOSDiskReadLatencyAlert_4b62cf77-069b-42a3-9608-8cd585a640f1.json, services/HybridCompute/machines/templates/arm/HybridMachineOSDiskWriteLatencyms_50ee79d0-a321-4217-8f5b-b096654ad1ce.json, services/HybridCompute/machines/templates/arm/HybridMachineProcessorUtilizationPercentage_639014b8-0ac6-4ae1-a887-bb3979669287.json, services/HybridCompute/machines/templates/bicep/HybridMachineAvailableMemoryPercentage_67300599-c61e-48d2-b47d-979b2254d494.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineDataDiskFreeSpacePercentageAlert_2030d931-6431-4134-9a03-106ebb83cb2d.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineDataDiskReadLatencyAlert_6aff7331-001f-4ee6-b5d2-1fc43b18b7de.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineDataDiskWriteLatencyAlert_c4226730-ae59-4607-bddc-03b91dad1c4b.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineHeartbeatAlert_7ade7362-3df1-4ad2-a000-78fa7b3d9b27.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineNetworkReadAlert_5e223d13-112e-4f84-82ba-e03a76f6350f.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineNetworkWriteAlert_bb1969d8-eaa2-45b6-bd9f-09348b1ee346.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineOSDiskFreeSpacePercentage_6a96dc94-674f-4a9c-830e-a0a4f7383646.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineOSDiskReadLatencyAlert_4b62cf77-069b-42a3-9608-8cd585a640f1.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineOSDiskWriteLatencyms_50ee79d0-a321-4217-8f5b-b096654ad1ce.bicep, services/HybridCompute/machines/templates/bicep/HybridMachineProcessorUtilizationPercentage_639014b8-0ac6-4ae1-a887-bb3979669287.bicep
[GitHub Action - Generate Templates] Generate templates for alerts
=> [GitHub Action - Generate Templates] Generate templates for alerts

docs/content/welcome/_index.md
Implemented a What's New section to AMBA. This showcases new improvements/solutions that were recently implemented successfully by the team. Each update was summarized into concise bullet points with corresponding links, details, and benefits in order to be easily digestible by readers.
1.  Adds a What's new section
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` …
=> Adding "What's New" Section to AMBA

patterns/alz/eslzArm.terraform-sync.param.json
Adds parameter file for TF sync process.
ALZ Library PR  for reference: https://github.com/Azure/Azure-Landing-Zones-Library/pull/93
1. Adds parameter file for TF sync process.
None
Used by: platform\amba-alz\scripts\Invoke-LibraryUpdatePolicyAssignmentArchetypes.ps1 in https://github.com/Azure/Azure-Landing-Zones-Library
Workflow:
Tasks that call the script, that calls the TF params:
=> Adds terraform-sync parameters

docs/content/patterns/alz/HowTo/Bring-your-own-Managed-Identity.md, docs/content/patterns/alz/HowTo/Bring-your-own-Notifications.md, docs/content/patterns/alz/HowTo/Cleaning-up-a-Deployment.md, docs/content/patterns/alz/HowTo/Telemetry.md, docs/content/patterns/alz/HowTo/Threshold-Override.md, docs/content/patterns/alz/HowTo/UpdateToNewReleases/Update_to_release_2024_12_10.md, docs/content/patterns/alz/HowTo/UpdateToNewReleases/_index.md, docs/content/patterns/alz/HowTo/deploy/Customize-Policy-Assignment.md, docs/content/patterns/alz/HowTo/deploy/Deploy-only-Service-Health-Alerts.md, docs/content/patterns/alz/HowTo/deploy/Deploy-with-Azure-CLI.md, docs/content/patterns/alz/HowTo/deploy/Deploy-with-Azure-PowerShell.md, docs/content/patterns/alz/HowTo/deploy/parameterConfiguration.md, docs/content/patterns/alz/Overview/Whats-New.md
1. *Updated documentation for release 2024.12.10*
2. *Tested the deployment through AMBA portal accelerator*
**Deploy in progress**
**Deploy completed**
1. *NONE*
=> New release documentation for 2024-12-10

docs/content/patterns/alz/HowTo/UpdateToNewReleases/Updating_to_release_2025-01-10.md, docs/content/patterns/alz/Overview/Whats-New.md
1. *Updates documentation for ALZ pattern with the new release info*
1. *NONE*
=> Updating documentation following up the new release

docs/content/welcome/_index.md
1. *Adds a note containing the link to the survey for our users to fill in*
1. *NONE*
=> AMBA - Feedback survey link on the welcome page

docs/content/faq/_index.md
Updates FAQ page with new information, such as questions and answers, and an intro background to what the FAQ page entails
1. Adds questions and answers to FAQ page
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/azure-monitor-baseline-alerts/issues) or ADO Work Items (Internal Only)
- x[ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
=> FAQ page update _index.md

patterns/alz/alzArm.json, patterns/alz/policyAssignments/DINE-WebAssignment.json
1. *Adds the Deploy-AMBA-Web identity to the Managed Identity Operator role on the Management management group to fix remediation task failure for Deploy Application Insights Throttling Limit Reached Alert (Preview)*
1. *Updating an existing deployment requires that existing role assignments are removed before the deployment. To remove them run the maintenance script using this syntax: _**.\patterns\alz\scripts\Start-AMBA-ALZ-maintenance.ps1 -pseudoRootManagementGroup $pseudoRootManagementGroup -cleanItems PolicyAssignments**_*
=> Missing identity assignment

services/Network/routeTables/alerts.yaml
=> Add Activity Log Alerts for Route Table and Route Deletion

docs/content/faq/_index.md
Enhancing FAQ page based on feedback by including links and information to Pattern/Scenario specific FAQ pages in order to create a more unified hub for user questions and answers across all of AMBA.
1. *Adds enhancements to FAQ page*
=> Update to FAQ page based on feedback

docs/content/patterns/alz/Resources/Known-Issues.md
1. *Adds a new scenario to the Known Issues section of the AMBA-ALZ documentation*
1. *NONE*
- [X ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/azure-monitor-baseline-alerts/)
=> Add documentation for InvalidPolicyParameterUpdate deployment error

.github/actions-pester/Test-Terraform-sync.Tests.ps1
1. *Fix an issue with the parsing of param object structure for ExclusionList*
1. *NONE*
=> Refactor parameter exclusion logic in Test-Terraform-sync.Tests.ps1

docs/content/contributing/_index.md
This pull request includes several small changes to the `docs/content/contributing/_index.md` file to correct typos and improve clarity in the documentation.
Documentation improvements:
* Corrected a typo in the phrase "without having to deal with the more advanced components of this site."
* Fixed typos in the alert properties and references descriptions.
* Corrected a typo in the note about the alert definition verification.
=> Update - Update _index.md

docs/content/patterns/alz/HowTo/deploy/Deploy-with-Terraform.md
Adding terraform documentation for deploying AMBA ALZ.
- Adds Deploy-with-Terraform.md
=> feat: terraform deployment documentation

docs/content/patterns/alz/HowTo/deploy/Introduction-to-deploying-the-ALZ-Pattern.md
1. *Fixes #600 which reported the broken link problem*
1. *NONE*
=> fix: AMBA - Diagrams.vsdx download link invalid

services/Compute/virtualMachines/alerts.yaml
Updating Disks AMBA with PG verified alerts, by updating thresholds, operators and properties.
1. *Updates alert properties with PG verified thresholds*
=> PG Verified alert updates for Disks

services/Compute/virtualMachines/templates/policy-arm/DataDiskBandwidthConsumedPercentage_b57b0749-f851-4c3d-b7fb-7cf26f3bf16a.json, services/Compute/virtualMachines/templates/policy-arm/DataDiskIOPSConsumedPercentage_b0cbb9f8-cc67-4e7d-95a8-5a058c6de7e0.json, services/Compute/virtualMachines/templates/policy-arm/OSDiskBandwidthConsumedPercentage_f7e19635-0118-4040-83d5-2f4c2150aef1.json, services/Compute/virtualMachines/templates/policy-arm/OSDiskFreeSpacePercentage_dca7af9f-cad2-4751-a61f-77d92c2ce523.json, services/Compute/virtualMachines/templates/policy-arm/OSDiskIOPSConsumedPercentage_a2bf3c43-d327-473b-9204-f77e2a0fe398.json, services/Compute/virtualMachines/templates/policy-arm/VMCachedBandwidthConsumedPercentage_eb85f15b-b705-418f-b8ed-93d8cc7a9a6c.json, services/Compute/virtualMachines/templates/policy-arm/VMCachedIOPSConsumedPercentage_c878115f-2a89-446e-8980-ef4f152120c5.json, services/Compute/virtualMachines/templates/policy-arm/VMUncachedBandwidthConsumedPercentage_e3981e7b-fd8b-4e07-bb68-d598c020c12d.json, services/Compute/virtualMachines/templates/policy-arm/VMUncachedIOPSConsumedPercentage_765ceb5b-ec1d-44d7-b94d-bb139030df81.json, services/Compute/virtualMachines/templates/policy/DataDiskBandwidthConsumedPercentage_b57b0749-f851-4c3d-b7fb-7cf26f3bf16a.json, services/Compute/virtualMachines/templates/policy/DataDiskIOPSConsumedPercentage_b0cbb9f8-cc67-4e7d-95a8-5a058c6de7e0.json, services/Compute/virtualMachines/templates/policy/OSDiskBandwidthConsumedPercentage_f7e19635-0118-4040-83d5-2f4c2150aef1.json, services/Compute/virtualMachines/templates/policy/OSDiskFreeSpacePercentage_dca7af9f-cad2-4751-a61f-77d92c2ce523.json, services/Compute/virtualMachines/templates/policy/OSDiskIOPSConsumedPercentage_a2bf3c43-d327-473b-9204-f77e2a0fe398.json, services/Compute/virtualMachines/templates/policy/VMCachedBandwidthConsumedPercentage_eb85f15b-b705-418f-b8ed-93d8cc7a9a6c.json, services/Compute/virtualMachines/templates/policy/VMCachedIOPSConsumedPercentage_c878115f-2a89-446e-8980-ef4f152120c5.json, services/Compute/virtualMachines/templates/policy/VMUncachedBandwidthConsumedPercentage_e3981e7b-fd8b-4e07-bb68-d598c020c12d.json, services/Compute/virtualMachines/templates/policy/VMUncachedIOPSConsumedPercentage_765ceb5b-ec1d-44d7-b94d-bb139030df81.json, services/DocumentDB/databaseAccounts/templates/policy-arm/DataUsage_0914c189-0adc-45d6-8704-d2ae73b9b7b6.json, services/DocumentDB/databaseAccounts/templates/policy-arm/MongoRequests_3f30e3aa-7e17-4eaf-a437-a420f5a23bf2.json, services/DocumentDB/databaseAccounts/templates/policy-arm/TotalRequests_2a1deb2d-1fc0-499b-a828-04aeece855fe.json, services/DocumentDB/databaseAccounts/templates/policy/DataUsage_0914c189-0adc-45d6-8704-d2ae73b9b7b6.json, services/DocumentDB/databaseAccounts/templates/policy/MongoRequests_3f30e3aa-7e17-4eaf-a437-a420f5a23bf2.json, services/DocumentDB/databaseAccounts/templates/policy/TotalRequests_2a1deb2d-1fc0-499b-a828-04aeece855fe.json
Generate policy templates based on updates to Cosmos DB and VM Disks
=> Generate policy templates based on updates to Cosmos DB and VM Disks

docs/content/patterns/alz/HowTo/deploy/Deploy-with-Terraform.md, docs/content/patterns/alz/Resources/Terraform-Module.md
update Terraform Module documentation for AMBA-ALZ deployment
1. update Terraform Module documentation for AMBA-ALZ deployment
2. Fixes #626
=> docs: update Terraform Module documentation for AMBA-ALZ deployment

patterns/alz/policyDefinitions/policies-Compute.json, patterns/alz/policyDefinitions/policies-Hybrid.json, patterns/alz/policyDefinitions/policies-Web.json, patterns/alz/policyDefinitions/policySets.json, patterns/alz/policySetDefinitions/Deploy-HybridVM-Alerts.json, patterns/alz/policySetDefinitions/Deploy-Management-Alerts.json, patterns/alz/policySetDefinitions/Deploy-VM-Alerts.json, patterns/alz/policySetDefinitions/Deploy-Web-Alerts.json
1. *Updates the default value for UAMI in the following policySetDefintions to fix issue #630*:
- Deploy-HybridVM-Alerts.json
- Deploy-Management-Alerts.json
- Deploy-VM-Alerts.json
- Deploy-Web-Alerts.json
1. *NONE*
=> BUG: UAMI default value is not correct

docs/content/patterns/alz/HowTo/UpdateToNewReleases/Update_to_release_2025-07-02.md, docs/content/patterns/alz/HowTo/UpdateToNewReleases/_index.md, docs/content/patterns/alz/HowTo/deploy/Customize-Policy-Assignment.md, docs/content/patterns/alz/HowTo/deploy/Deploy-with-Azure-CLI.md, docs/content/patterns/alz/HowTo/deploy/Deploy-with-Azure-PowerShell.md, docs/content/patterns/alz/HowTo/deploy/Preview-Deploy-Changes.md, docs/content/patterns/alz/Overview/Whats-New.md
1. *Documents the new release*
2. *Documents the procedure to update to the new release*
1. *NONE*
=> New 2025-07-02 release documentation
